# Generated by Django 4.1.2 on 2022-10-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('long_effect', models.TextField(blank=True, null=True)),
                ('short_effect', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.CreateModel(
            name='PokemonTypeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_types', to='pokedex.pokemon')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='pokedex.pokemontype')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(related_name='pokemon', to='pokedex.ability'),
        ),
    ]
