# Generated by Django 4.1.2 on 2022-10-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_remove_pokemon_abilities_pokemonabilityslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='pokeapi_id',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
