# Generated by Django 4.1.2 on 2022-10-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_ability_pokeapi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='official_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
