# Generated by Django 4.1.2 on 2022-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_pokemon_official_image_url_pokemon_sprite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
